

 #region SERVICES

Get-Service -Name *MongoDB*

 

#Start \Stop services

 Stop-Service 'MongoDB'

 Start-Service 'MongoDB'
 
 #endregion

 #region application
 
 cd .\MongoDB\bin

 .\mongo.exe --help


 #MongoDBDriver
 Install-Package MongoDB.Driver


 #.\mongod.exe --install --serviceName "Mongod" --serviceDisplayName "Mongo service deamon" --serviceDescription "MongoDB service"  --logpath c:\data\Mongo.log

 #load the C# drivers and connect to the Mongodb database.

$mongoDriverPath = "c:\MongoDB\CSharpDriver 1.7"
Add-Type -Path "$($mongoDriverPath)\MongoDB.Bson.dll"
Add-Type -Path "$($mongoDriverPath)\MongoDB.Driver.dll"

 

 #endregion


  #region Driver detail
  

  #MongoDBDriver
 Install-Package MongoDB.Driver

 PS C:\MongoDB\bin>  Install-Package MongoDB.Driver

Name                           Version          Source           Summary                                                                                                                                                                                         
----                           -------          ------           -------                                                                                                                                                                                         
Microsoft.NETCore.Platforms    2.0.0            https://www.n... Provides runtime information required to resolve target framework, platform, and runtime specific implementations of .NETCore packages. ...                                                     
Microsoft.NETCore.Targets      2.0.0            https://www.n... Provides supporting infrastructure for portable projects: support identifiers that define framework and runtime for support targets and packages that reference the minimum supported package...
System.Runtime                 4.3.0            https://www.n... Provides the fundamental primitives, classes and base classes that define commonly-used value and reference data types, events and event handlers, interfaces, attributes, and exceptions. Th...
System.Text.Encoding           4.3.0            https://www.n... Provides base abstract encoding classes for converting blocks of characters to and from blocks of bytes....                                                                                     
System.Threading.Tasks         4.3.0            https://www.n... Provides types that simplify the work of writing concurrent and asynchronous code....                                                                                                           
System.IO                      4.3.0            https://www.n... Provides base input and output (I/O) types, including System.IO.Stream, System.IO.StreamReader and System.IO.StreamWriter, that allow reading and writing to data streams...                    
System.Reflection.Primitives   4.3.0            https://www.n... Provides common enumerations for reflection-based libraries....                                                                                                                                 
System.Reflection              4.3.0            https://www.n... Provides types that retrieve information about assemblies, modules, members, parameters, and other entities in managed code by examining their metadata. These types also can be used to mani...
System.Reflection.Extensions   4.3.0            https://www.n... Provides custom attribute extension methods for System.Reflection types....                                                                                                                     
System.Globalization           4.3.0            https://www.n... Provides classes that define culture-related information, including language, country/region, calendars in use, format patterns for dates, currency, and numbers, and sort order for strings....
System.Resources.ResourceMa... 4.3.0            https://www.n... Provides classes and attributes that allow developers to create, store, and manage various culture-specific resources used in an application....                                                
System.Threading               4.3.0            https://www.n... Provides the fundamental synchronization primitives, including System.Threading.Monitor and System.Threading.Mutex, that are required when writing asynchronous code....                        
runtime.native.System          4.3.0            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
System.Runtime.Handles         4.3.0            https://www.n... Provides base classes, including System.Runtime.InteropServices.CriticalHandle and System.Runtime.InteropServices.SafeHandle, for types that represent operating system handles....             
System.Runtime.InteropServices 4.3.0            https://www.n... Provides types that support COM interop and platform invoke services....                                                                                                                        
System.Runtime.InteropServi... 4.3.0            https://www.n... Provides APIs to query about runtime and OS information....                                                                                                                                     
Microsoft.Win32.Primitives     4.3.0            https://www.n... Provides common types for Win32-based libraries....                                                                                                                                             
System.Collections             4.3.0            https://www.n... Provides classes that define generic collections, which allow developers to create strongly typed collections that provide better type safety and performance than non-generic strongly typed...
System.AppContext              4.3.0            https://www.n... Provides the System.AppContext class, which allows access to the BaseDirectory property and other application specific data....                                                                 
System.Console                 4.3.0            https://www.n... Provides the System.Console class, which represents the standard input, output and error streams for console applications....                                                                   
System.Globalization.Calendars 4.3.0            https://www.n... Provides classes for performing date calculations using specific calendars, including the Gregorian, Julian, Hijri and Korean calendars....                                                     
runtime.native.System.IO.Co... 4.3.0            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
System.Diagnostics.Debug       4.3.0            https://www.n... Provides classes and attributes that allows basic interaction with a debugger....                                                                                                               
System.Diagnostics.Tracing     4.3.0            https://www.n... Provides class that enable you to create high performance tracing events to be captured by event tracing for Windows (ETW)....                                                                  
System.Buffers                 4.4.0            https://www.n... Provides resource pooling of any type for performance-critical applications that allocate and deallocate objects frequently....                                                                 
System.Runtime.Extensions      4.3.0            https://www.n... Provides commonly-used classes for performing mathematical functions, conversions, string comparisons and querying environment information....                                                  
System.IO.Compression          4.3.0            https://www.n... Provides classes that support the compression and decompression of streams....                                                                                                                  
System.IO.FileSystem.Primit... 4.3.0            https://www.n... Provides common enumerations and exceptions for path-based I/O libraries....                                                                                                                    
System.IO.FileSystem           4.3.0            https://www.n... Provides types that allow reading and writing to files and types that provide basic file and directory support....                                                                              
System.IO.Compression.ZipFile  4.3.0            https://www.n... Provides classes that support the compression and decompression of streams using file system paths....                                                                                          
System.Security.Cryptograph... 4.3.0            https://www.n... Provides common types for the cryptographic libraries....                                                                                                                                       
runtime.debian.8-x64.runtim... 4.3.1            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
runtime.fedora.23-x64.runti... 4.3.1            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
runtime.fedora.24-x64.runti... 4.3.1            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
runtime.opensuse.13.2-x64.r... 4.3.1            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
runtime.opensuse.42.1-x64.r... 4.3.1            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
runtime.osx.10.10-x64.runti... 4.3.1            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
runtime.rhel.7-x64.runtime.... 4.3.1            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
runtime.ubuntu.14.04-x64.ru... 4.3.1            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
runtime.ubuntu.16.04-x64.ru... 4.3.1            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
runtime.ubuntu.16.10-x64.ru... 4.3.1            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
runtime.native.System.Secur... 4.3.1            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
System.Collections.Concurrent  4.3.0            https://www.n... Provides several thread-safe collection classes that should be used in place of the corresponding types in the System.Collections.NonGeneric and System.Collections packages whenever multipl...
System.Linq                    4.3.0            https://www.n... Provides classes and interfaces that supports queries that use Language-Integrated Query (LINQ)....                                                                                             
System.Security.Cryptograph... 4.3.0            https://www.n... Provides types for representing Abstract Syntax Notation One (ASN.1)-encoded data....                                                                                                           
runtime.osx.10.10-x64.runti... 4.3.0            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
runtime.native.System.Secur... 4.3.0            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
System.Runtime.Numerics        4.3.0            https://www.n... Provides the numeric types System.Numerics.BigInteger and System.Numerics.Complex, which complement the numeric primitives, such as System.Byte, System.Double and System.Int32....             
System.Security.Cryptograph... 4.3.0            https://www.n... Provides base types for cryptographic algorithms, including hashing, encryption, and signing operations....                                                                                     
System.Security.Cryptograph... 4.4.0            https://www.n... Provides cryptographic algorithm implementations and key management with Windows Cryptographic Next Generation API (CNG)....                                                                    
runtime.native.System.Net.Http 4.3.0            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
System.Security.Cryptograph... 4.3.0            https://www.n... Provides cryptographic algorithm implementations and key management with Windows Cryptographic API (CryptoAPI)....                                                                              
System.Security.Cryptograph... 4.3.0            https://www.n... Provides cryptographic algorithm implementations and key management for non-Windows systems with OpenSSL....                                                                                    
System.Security.Cryptograph... 4.3.0            https://www.n... Provides types for reading, exporting and verifying Authenticode X.509 v3 certificates. These certificates are signed with a private key that uniquely and positively identifies the holder o...
System.Diagnostics.Diagnost... 4.4.1            https://www.n... Provides Classes that allow you to decouple code logging rich (unserializable) diagnostics/telemetry (e.g. framework) from code that consumes it (e.g. tools)...                                
System.Net.Primitives          4.3.0            https://www.n... Provides common types for network-based libraries, including System.Net.IPAddress, System.Net.IPEndPoint, and System.Net.CookieContainer....                                                    
System.ObjectModel             4.3.0            https://www.n... Provides types and interfaces that allow the creation of observable types that provide notifications to clients when changes are made to it....                                                 
System.Runtime.WindowsRuntime  4.3.0            https://www.n... Provides extensions methods that improve interoperation between managed code and the Windows Runtime....                                                                                        
System.Text.Encoding.Extens... 4.3.0            https://www.n... Provides support for specific encodings, including ASCII, UTF-7, UTF-8, UTF-16, and UTF-32....                                                                                                  
System.Globalization.Extens... 4.3.0            https://www.n... Provides classes for performing Unicode string normalization, culture-specific string comparisons and support the use of non-ASCII characters for Internet domain names....                     
System.Net.Http                4.3.2            https://www.n... Provides a programming interface for modern HTTP applications, including HTTP client components that allow applications to consume web services over HTTP and HTTP components that can be use...
System.Net.Sockets             4.3.0            https://www.n... Provides classes such as Socket, TcpClient and UdpClient, which enable developers to send and receive data over the network....                                                                 
System.Text.RegularExpressions 4.3.0            https://www.n... Provides the System.Text.RegularExpressions.Regex class, an implementation of a regular expression engine....                                                                                   
System.Threading.Tasks.Exte... 4.4.0            https://www.n... Provides additional types that simplify the work of writing concurrent and asynchronous code....                                                                                                
System.Xml.ReaderWriter        4.3.0            https://www.n... Provides provides a fast, non-cached, forward-only way to read and write Extensible Markup Language (XML) data....                                                                              
System.Diagnostics.Tools       4.3.0            https://www.n... Provides attributes, such as GeneratedCodeAttribute and SuppresMessageAttribute, that are emitted or consumed by analysis tools....                                                             
System.Reflection.Emit.ILGe... 4.3.0            https://www.n... Provides classes that allow a compiler or tool to emit Microsoft intermediate language (MSIL). The primary clients of these classes are script engines and compilers....                        
System.Reflection.Emit.Ligh... 4.3.0            https://www.n... Provides the System.Reflection.Emit.DynamicMethod class, which represents a dynamic method that can be compiled, executed, and discarded. Discarded methods are available for garbage collect...
System.Diagnostics.Contracts   4.3.0            https://www.n... Provides static classes for representing program contracts such as preconditions, postconditions, and invariants....                                                                            
System.Reflection.TypeExten... 4.4.0            https://www.n... Provides extensions methods for System.Type that are designed to be source-compatible with older framework reflection-based APIs....                                                            
System.Reflection.Emit         4.3.0            https://www.n... Provides classes that allow a compiler or tool to emit metadata and optionally generate a PE file on disk. The primary clients of these classes are script engines and compilers....            
System.Linq.Expressions        4.3.0            https://www.n... Provides classes, interfaces and enumerations that enable language-level code expressions to be represented as objects in the form of expression trees....                                      
System.Xml.XDocument           4.3.0            https://www.n... Provides the classes for Language-Integrated Query (LINQ) to Extensible Markup Language (XML). LINQ to XML is an in-memory XML programming interface that enables you to modify XML documents...
System.Threading.Timer         4.3.0            https://www.n... Provides the System.Threading.Timer class, which is a mechanism for executing a method at specified intervals....                                                                               
NETStandard.Library            2.0.0            https://www.n... A set of standard .NET APIs that are prescribed to be used and supported together. ...                                                                                                          
System.Collections.NonGeneric  4.3.0            https://www.n... Provides classes that define older non-generic collections of objects, such as lists, queues, hash tables and dictionaries. Developers should prefer the generic collections in the System.Co...
System.Security.Principal      4.3.0            https://www.n... Provides the base interfaces for principal and identity objects that represents the security context under which code is running....                                                            
System.Security.Claims         4.3.0            https://www.n... Provides classes that implement claims-based identity in the .NET Framework, including classes that represent claims, claims-based identities, and claims-based principals....                  
System.Security.Principal.W... 4.4.0            https://www.n... Provides classes for retrieving the current Windows user and for interacting with Windows users and groups....                                                                                  
System.Threading.Thread        4.3.0            https://www.n... Provides the System.Threading.Thread class, which allows developers to create and control a thread, set its priority, and get its state....                                                     
System.Security.AccessControl  4.4.0            https://www.n... Provides base classes that enable managing access and audit control lists on securable objects....                                                                                              
Microsoft.Win32.Registry       4.4.0            https://www.n... Provides support for accessing and modifying the Windows Registry....                                                                                                                           
System.Threading.ThreadPool    4.3.0            https://www.n... Provides the System.Threading.ThreadPool class, which contains a pool of threads that can be used to execute tasks, post work items, wait on behalf of other threads, and process timers....    
System.Diagnostics.Process     4.3.0            https://www.n... Provides the System.Diagnostics.Process class, which allows interaction with local and remote processes....                                                                                     
System.Dynamic.Runtime         4.3.0            https://www.n... Provides classes and interfaces that support the Dynamic Language Runtime (DLR)                                                                              
MongoDB.Bson                   2.4.4            https://www.n... MongoDBs Official Bson Library                                                                                                                                                            
System.Collections.Specialized 4.3.0            https://www.n... Provides older specialized non-generic collections; for example, a linked list dictionary, a bit vector, and collections that contain only strings....                                          
System.Diagnostics.TraceSource 4.3.0            https://www.n... Provides classes that help you trace the execution of your code. Developers should prefer the classes in the ETW-based System.Diagnostics.Tracing package....                                   
System.Net.NameResolution      4.3.0            https://www.n... Provides the System.Net.Dns class, which enables developers to perform simple domain name resolution....                                                                                        
runtime.native.System.Net.S... 4.3.0            https://www.n... Internal implementation package not meant for direct consumption.  Please do not reference directly. ...                                                                                        
System.Net.Security            4.3.1            https://www.n... Provides types, such as System.Net.Security.SslStream, that uses SSL/TLS protocols to provide secure network communication between client and server endpoints....                              
System.Security.SecureString   4.3.0            https://www.n... Provides the System.Security.SecureString class, which represents text that should be kept confidential. The text is encrypted for privacy when being used, and deleted from computer memory ...
MongoDB.Driver.Core            2.4.4            https://www.n... Core Component of the Official MongoDB .NET Driver.                                                                                                                                             
System.Linq.Queryable          4.3.0            https://www.n... Provides classes for querying data structures that implement IQueryable<T>....                                                                                                                  
MongoDB.Driver                 2.4.4            https://www.n... Official .NET driver for MongoDB

#endregion